#!/usr/bin/env python3
"""Snatcher Korean patch — frozen 0.3.2 pipeline.  THE official entry point.

Run this, not the individual stage scripts.  It pins every parameter that the
three stages used to take by hand, so a build is reproducible from the master
TSVs alone:

    python build_snatcher_ko_0_3_2.py              full build (stages 1-3)
    python build_snatcher_ko_0_3_2.py --stage3     stage 3 only, reusing stage 1/2
    python build_snatcher_ko_0_3_2.py --check      validate inputs, build nothing

0.3.2 — scene packs stop overwriting each other
-----------------------------------------------
Every scene pack was built with destination $50000, one slot, so reopening a
menu whose records lived in a different pack than the surrounding dialogue paid
a full CD load each time.  Measured: scene_111800 re-read seven times and
scene_10F800 five times in one session, alternating.  They total 102 KB against
a 1.7 MB scene region, so the overlay bought nothing.  Each pack now gets its
own address and its own loaded-flag, which also let the helper drop its scene
branches (709 -> 664 B).  The pack metadata table moved from +$80 to +$20,
raising the ceiling from 16 packs to 28; the 2026-08-14 master needs 25.

0.3.1 — AC layout fix
---------------------
0.3.0 put the resident packs at a hardcoded $16000 without ever consulting the
atlas.  The packs transfer after the initial load, so any atlas past 741 glyphs
was overwritten from its tail: 0.3.0's 1,089-glyph atlas lost 348 glyphs and
they stayed lost until a power cycle, because the init run is MAGIC-guarded.
The floor is now derived from the initial load's chunk-padded extent, and an
extent audit fails the build on any overlap.  Nothing else changed — with an
atlas that fits under $16000 this emits the same bytes 0.3.0 did.

Version history behind this number
----------------------------------
The engine is the verified ``0.3.0-uitest`` renderer.  ``ac_0.1.1`` through
``ac_0.1.18`` were the Arcade Card backing-store development series on top of
it; ``ac_0.1.14`` was the last one and is the shipped disc.  0.3.0 promotes that
combination to the project's single version number.  The AC series numbers are
retired — see ``_archive/build_records/DELETED_BUILDS_2026-08-13.md``.

What is frozen
--------------
    engine            0.3.0-uitest renderer.  $66E5 hook, $5E40 preloader,
                      $7F50 font wrapper, $5B80-$5E3F 704 B cache.  Do not
                      redesign these.
    record format     128 B compact record + global glyph atlas, expanded back
                      to a byte-identical 704 B payload by the Bank 69 helper
    CHUNK_BYTES       8 KiB.  Hard ceiling — above it the BIOS loses the AC
                      auto-increment pointer at a bank boundary
    stage 1 base      ac_0.1.11-source (intermediate, not a release)
    inclusion         BODY: first unnamed review column is O (예외처리 = context
                      -only continuation).  UI: review column is O.
                      ko_text or status alone never ships a row.

Inputs — the only canonical ones
--------------------------------
    snatcher_tool/translation/snatcher_ko_master.tsv
    snatcher_tool/translation/ui_text.tsv
    snatcher_tool/translation/speaker_name_standard.tsv

Edit them through SnatcherTranslationStudio.exe.  Close Studio before touching
them from outside, or Studio will write back its stale review column on save.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

STATIC = Path(__file__).resolve().parent
ROOT = STATIC.parents[2]
sys.path.insert(0, str(STATIC))

VERSION = "0.3.2"
STAGE1_VERSION = "ac_0.1.11-source"
STAGE1_BUILD = ROOT / "build" / "patch" / STAGE1_VERSION
OUT = ROOT / "build" / "patch" / VERSION

TRANSLATION = ROOT / "snatcher_tool" / "translation"
CANONICAL_INPUTS = (
    TRANSLATION / "snatcher_ko_master.tsv",
    TRANSLATION / "ui_text.tsv",
    TRANSLATION / "speaker_name_standard.tsv",
    # Stage 3 copies this into the build folder as a provenance record, so a
    # missing file fails the build at the very last step.  It is regenerated by
    # extraction/translation/exclude_reported_master_conflicts.py and lists the
    # rows whose review mark was withdrawn because the game cannot tell the
    # Japanese sources apart.
    TRANSLATION / "master_conflict_exclusions.tsv",
)


# A build costs ~200 MB of real disk: the patched Track 02 and Track 24.  The
# other 22 tracks are hardlinks into rom(japan) and cost nothing.  Without
# pruning, every build kept that 200 MB forever.  Records -- manifests, TSVs,
# verification logs -- total under 5 MB across every build ever made and are
# what makes an old build auditable, so pruning drops payload only.
# Keep the BODY 0.2.26 control build available for save/overlay regression
# testing.  Its cue is unusable if the automatic post-build prune removes the
# referenced Track 02/24 payloads.
PROTECTED = {VERSION, STAGE1_VERSION, "ac_0.1.14", "0.2.26"}
PAYLOAD_SUFFIXES = (".bin", ".chd")


def prune(deep: bool = False) -> None:
    """Delete disc payloads from superseded builds, keeping their records.

    ``deep`` also drops the stage 1/2 intermediate, which costs the next build
    its ``--stage3`` shortcut but reclaims another ~240 MB.
    """
    protected = PROTECTED - ({STAGE1_VERSION} if deep else set())
    root = ROOT / "build" / "patch"
    freed = unlinked = 0
    for build in sorted(p for p in root.iterdir() if p.is_dir()):
        if build.name in protected:
            continue
        for path in sorted(build.rglob("*")):
            if not path.is_file() or path.suffix.lower() not in PAYLOAD_SUFFIXES:
                continue
            stat = path.stat()
            # A hardlinked track shares its inode with rom(japan), so removing
            # this name frees nothing.  Drop it anyway to keep the folder
            # honest, but do not claim the bytes back.
            if stat.st_nlink > 1:
                unlinked += 1
            else:
                freed += stat.st_size
            path.unlink()
    if freed or unlinked:
        print(f"pruned {freed / 1e6:,.0f} MB "
              f"({unlinked} hardlinked track names also dropped); "
              f"kept {', '.join(sorted(protected))}")


def check_inputs() -> None:
    missing = [p for p in CANONICAL_INPUTS if not p.exists()]
    if missing:
        raise SystemExit(
            "missing canonical input(s):\n  "
            + "\n  ".join(str(p) for p in missing)
        )

    sys.path.insert(0, str(ROOT / "extraction" / "translation"))
    import build_full_overlay_layout as layout
    from tsv_io import read_dict_rows

    selected, exceptions = layout.reviewed_row_ids(TRANSLATION / "snatcher_ko_master.tsv")
    ui_header, ui_rows = read_dict_rows(TRANSLATION / "ui_text.tsv")
    review = layout.ui_review_column(ui_header)
    ui_ok = [r for r in ui_rows
             if r.get("ko_text", "").strip()
             and r.get("status", "") != "skip"
             and layout.is_ui_reviewed(r, review)]
    ui_translated = [r for r in ui_rows if r.get("ko_text", "").strip()]

    print(f"BODY  reviewed rows : {len(selected):,} (예외처리 {len(exceptions)})")
    print(f"UI    review column : {review!r}")
    print(f"UI    translated    : {len(ui_translated):,} / {len(ui_rows):,}")
    print(f"UI    review = O    : {len(ui_ok):,}   <- this is what ships")
    if ui_translated and not ui_ok:
        print()
        print("  NOTE: every UI row is unreviewed, so this build ships 0 UI labels.")
        print("  A UI label sits in a fixed cell count (action menu = 8 cells of 8")
        print("  characters), so a translation that has not been seen on screen is")
        print("  not shippable. Mark verified rows O in the Studio UI tab.")


def stage(argv: list[str], title: str) -> None:
    print(f"\n=== {title} ===", flush=True)
    # Pin the translator workspace rather than trusting the ambient default.
    # Stage 1 resolves --master/--speakers/--ui from SNATCHER_TRANSLATION_DIR.
    env = dict(os.environ, SNATCHER_TRANSLATION_DIR=str(TRANSLATION))
    result = subprocess.run([sys.executable, *argv], cwd=str(ROOT), env=env)
    if result.returncode != 0:
        raise SystemExit(f"{title} failed (exit {result.returncode})")


def main() -> None:
    global VERSION, OUT, STAGE1_VERSION, STAGE1_BUILD

    parser = argparse.ArgumentParser(description=f"build Snatcher KO {VERSION}")
    parser.add_argument("--stage3", action="store_true",
                        help="rebuild only stage 3, reusing the existing "
                             f"{STAGE1_VERSION} intermediate")
    parser.add_argument("--check", action="store_true",
                        help="report what would ship, then stop")
    parser.add_argument("--prune", action="store_true",
                        help="delete superseded builds' disc payload, then stop")
    parser.add_argument("--deep", action="store_true",
                        help=f"with --prune, also drop the {STAGE1_VERSION} "
                             "intermediate (costs the next build its --stage3)")
    parser.add_argument("--space", choices=("8140", "F041", "20"), default="8140",
                        help="byte sequence a Korean word space compiles to. "
                             "8140 = native full cell (default, what ships). "
                             "F041 = reserved fractional space, two per cursor "
                             "unit. 20 = the renderer's single-byte space "
                             "branch. Non-default values build into a suffixed "
                             "folder and are experiments, not releases.")
    parser.add_argument("--tag", default="",
                        help="suffix the build and its stage 1/2 intermediate "
                             "with this name. Use it when the experiment is in "
                             "the translation data rather than in a flag, so "
                             "the release folder is never overwritten.")
    args = parser.parse_args()

    suffix = ""
    if args.space != "8140":
        os.environ["SNATCHER_KO_SPACE"] = args.space
        suffix += f"-space{args.space}"
        print(f"space experiment: Korean word spaces compile to {args.space}")
    if args.tag:
        suffix += f"-{args.tag}"

    if suffix:
        # Keep the release build untouched: an experiment gets its own folder
        # and its own name so a stray disc can never be mistaken for 0.3.1.
        #
        # The stage 1/2 intermediate has to fork too.  It is normally shared
        # under one fixed name, so an experiment writing into it would leave a
        # later plain --stage3 silently emitting the experiment's byte stream
        # with a release name on it.
        VERSION = f"{VERSION}{suffix}"
        STAGE1_VERSION = f"{STAGE1_VERSION}{suffix}"
        OUT = ROOT / "build" / "patch" / VERSION
        STAGE1_BUILD = ROOT / "build" / "patch" / STAGE1_VERSION
        PROTECTED.update({VERSION, STAGE1_VERSION})
        print(f"  stage 1/2 -> {STAGE1_BUILD}")
        print(f"  output    -> {OUT}")

    if args.prune:
        prune(deep=args.deep)
        return

    check_inputs()
    if args.check:
        return

    if args.stage3:
        if not STAGE1_BUILD.exists():
            raise SystemExit(
                f"--stage3 needs {STAGE1_BUILD}, which is missing. "
                "Run without --stage3 to regenerate it.")
        print(f"\nreusing stage 1/2 intermediate: {STAGE1_BUILD}")
    else:
        stage([str(STATIC / "build_direct_overlay_patch_ui.py"),
               "--version", STAGE1_VERSION, "--review-only", "--force"],
              "stage 1  master -> 704 B SRT4 records")
        stage([str(STATIC / "build_ac_backing_store.py"),
               "--build", str(STAGE1_BUILD)],
              "stage 2  sparse slots -> dense record image")

    print("\n=== stage 3  compact 128 B + atlas + AC packs + disc ===", flush=True)
    import build_ac_dynamic_0_1_14 as stage3

    # Same wrapper pattern the AC series used: retarget the shared dynamic
    # module, then run the pinned stage 3.  The emitted helper is unchanged.
    dynamic = stage3.dynamic
    dynamic.VERSION = VERSION
    dynamic.OUT = OUT
    # BASE is hardcoded to the shared intermediate in build_ac_dynamic_0_1_11.
    # A --space run forks that folder, so stage 3 has to be pointed at the fork
    # or it would rebuild the release intermediate under the experiment's name.
    dynamic.BASE = STAGE1_BUILD
    stage3.main()

    print(f"\n{VERSION} -> {OUT}")


if __name__ == "__main__":
    main()
