#!/usr/bin/env python3
"""Snatcher Korean patch — frozen 0.3.0 pipeline.  THE official entry point.

Run this, not the individual stage scripts.  It pins every parameter that the
three stages used to take by hand, so a build is reproducible from the master
TSVs alone:

    python build_snatcher_ko_0_3_0.py              full build (stages 1-3)
    python build_snatcher_ko_0_3_0.py --stage3     stage 3 only, reusing stage 1/2
    python build_snatcher_ko_0_3_0.py --check      validate inputs, build nothing

Version history behind this number
----------------------------------
The engine is the verified ``0.3.0-uitest`` renderer.  ``ac_0.1.1`` through
``ac_0.1.18`` were the Arcade Card backing-store development series on top of
it; ``ac_0.1.14`` was the last one and is the shipped disc.  0.3.0 promotes that
combination to the project's single version number.  The AC series numbers are
retired — see ``_archive/build_records/DELETED_BUILDS_2026-08-13.md``.

What is frozen
--------------
    engine            0.3.0-uitest renderer.  $66E5 hook, $5E40 preloader,
                      $7F50 font wrapper, $5B80-$5E3F 704 B cache.  Do not
                      redesign these.
    record format     128 B compact record + global glyph atlas, expanded back
                      to a byte-identical 704 B payload by the Bank 69 helper
    CHUNK_BYTES       8 KiB.  Hard ceiling — above it the BIOS loses the AC
                      auto-increment pointer at a bank boundary
    stage 1 base      ac_0.1.11-source (intermediate, not a release)
    inclusion         BODY: first unnamed review column is O (예외처리 = context
                      -only continuation).  UI: review column is O.
                      ko_text or status alone never ships a row.

Inputs — the only canonical ones
--------------------------------
    snatcher_tool/translation/snatcher_ko_master.tsv
    snatcher_tool/translation/ui_text.tsv
    snatcher_tool/translation/speaker_name_standard.tsv

Edit them through SnatcherTranslationStudio.exe.  Close Studio before touching
them from outside, or Studio will write back its stale review column on save.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

STATIC = Path(__file__).resolve().parent
ROOT = STATIC.parents[2]
sys.path.insert(0, str(STATIC))

VERSION = "0.3.0"
STAGE1_VERSION = "ac_0.1.11-source"
STAGE1_BUILD = ROOT / "build" / "patch" / STAGE1_VERSION
OUT = ROOT / "build" / "patch" / VERSION

TRANSLATION = ROOT / "snatcher_tool" / "translation"
CANONICAL_INPUTS = (
    TRANSLATION / "snatcher_ko_master.tsv",
    TRANSLATION / "ui_text.tsv",
    TRANSLATION / "speaker_name_standard.tsv",
    # Stage 3 copies this into the build folder as a provenance record, so a
    # missing file fails the build at the very last step.  It is regenerated by
    # extraction/translation/exclude_reported_master_conflicts.py and lists the
    # rows whose review mark was withdrawn because the game cannot tell the
    # Japanese sources apart.
    TRANSLATION / "master_conflict_exclusions.tsv",
)


def check_inputs() -> None:
    missing = [p for p in CANONICAL_INPUTS if not p.exists()]
    if missing:
        raise SystemExit(
            "missing canonical input(s):\n  "
            + "\n  ".join(str(p) for p in missing)
        )

    sys.path.insert(0, str(ROOT / "extraction" / "translation"))
    import build_full_overlay_layout as layout
    from tsv_io import read_dict_rows

    selected, exceptions = layout.reviewed_row_ids(TRANSLATION / "snatcher_ko_master.tsv")
    ui_header, ui_rows = read_dict_rows(TRANSLATION / "ui_text.tsv")
    review = layout.ui_review_column(ui_header)
    ui_ok = [r for r in ui_rows
             if r.get("ko_text", "").strip()
             and r.get("status", "") != "skip"
             and layout.is_ui_reviewed(r, review)]
    ui_translated = [r for r in ui_rows if r.get("ko_text", "").strip()]

    print(f"BODY  reviewed rows : {len(selected):,} (예외처리 {len(exceptions)})")
    print(f"UI    review column : {review!r}")
    print(f"UI    translated    : {len(ui_translated):,} / {len(ui_rows):,}")
    print(f"UI    review = O    : {len(ui_ok):,}   <- this is what ships")
    if ui_translated and not ui_ok:
        print()
        print("  NOTE: every UI row is unreviewed, so this build ships 0 UI labels.")
        print("  A UI label sits in a fixed cell count (action menu = 8 cells of 8")
        print("  characters), so a translation that has not been seen on screen is")
        print("  not shippable. Mark verified rows O in the Studio UI tab.")


def stage(argv: list[str], title: str) -> None:
    print(f"\n=== {title} ===", flush=True)
    # Pin the translator workspace rather than trusting the ambient default.
    # Stage 1 resolves --master/--speakers/--ui from SNATCHER_TRANSLATION_DIR.
    env = dict(os.environ, SNATCHER_TRANSLATION_DIR=str(TRANSLATION))
    result = subprocess.run([sys.executable, *argv], cwd=str(ROOT), env=env)
    if result.returncode != 0:
        raise SystemExit(f"{title} failed (exit {result.returncode})")


def main() -> None:
    parser = argparse.ArgumentParser(description=f"build Snatcher KO {VERSION}")
    parser.add_argument("--stage3", action="store_true",
                        help="rebuild only stage 3, reusing the existing "
                             f"{STAGE1_VERSION} intermediate")
    parser.add_argument("--check", action="store_true",
                        help="report what would ship, then stop")
    args = parser.parse_args()

    check_inputs()
    if args.check:
        return

    if args.stage3:
        if not STAGE1_BUILD.exists():
            raise SystemExit(
                f"--stage3 needs {STAGE1_BUILD}, which is missing. "
                "Run without --stage3 to regenerate it.")
        print(f"\nreusing stage 1/2 intermediate: {STAGE1_BUILD}")
    else:
        stage([str(STATIC / "build_direct_overlay_patch_ui.py"),
               "--version", STAGE1_VERSION, "--review-only", "--force"],
              "stage 1  master -> 704 B SRT4 records")
        stage([str(STATIC / "build_ac_backing_store.py"),
               "--build", str(STAGE1_BUILD)],
              "stage 2  sparse slots -> dense record image")

    print("\n=== stage 3  compact 128 B + atlas + AC packs + disc ===", flush=True)
    import build_ac_dynamic_0_1_14 as stage3

    # Same wrapper pattern the AC series used: retarget the shared dynamic
    # module, then run the pinned stage 3.  The emitted helper is unchanged.
    dynamic = stage3.dynamic
    dynamic.VERSION = VERSION
    dynamic.OUT = OUT
    stage3.main()

    print(f"\n{VERSION} -> {OUT}")


if __name__ == "__main__":
    main()
