-- SUB 0.3.5 -- 키 조회 성공 뒤(count_ok) VRAM 자리만 변경
-- 실행 대상: 현재 subtitle collection/keyed 판의 E6800_0E 첫 자막

SUB_ALLOCATOR_VERSION = '0.3.5'
SUB_ALLOCATOR_INPLACE_IMAGES = true
SUB_ALLOCATOR_TARGET_END = 0x6800
SUB_ALLOCATOR_PATCH_AT_COUNT_OK = true
dofile('C:/snatcher/lua/POC_SUBTITLE_DYNAMIC_FRAGMENT_ALLOCATOR_0_3_1.lua')
SUB_ALLOCATOR_VERSION = nil
SUB_ALLOCATOR_INPLACE_IMAGES = nil
SUB_ALLOCATOR_TARGET_END = nil
SUB_ALLOCATOR_PATCH_AT_COUNT_OK = nil
