-- SUB 0.4.33 -- 음성별 미니 색인. 1,912항목 선형검색을 완전히 제거한다.
SUB_VOICE_KEY_VERSION = '0.4.33'
SUB_VOICE_ENGINE_PATH = 'C:/snatcher/build/cutscene_subs/engine_ac_timed_safe_lua_mini.bin'
SUB_VOICE_ENGINE_BYTES = 652
SUB_VOICE_SELECTOR = 366
SUB_VOICE_NEXT_SELECTOR = 446
SUB_VOICE_MINI_INDEX = 0x1EF000
SUB_VOICE_MINI_COUNT = 5
dofile('C:/snatcher/lua/SUB/0.4.31.lua')
SUB_VOICE_KEY_VERSION = nil
SUB_VOICE_ENGINE_PATH = nil
SUB_VOICE_ENGINE_BYTES = nil
SUB_VOICE_SELECTOR = nil
SUB_VOICE_NEXT_SELECTOR = nil
SUB_VOICE_MINI_INDEX = nil
SUB_VOICE_MINI_COUNT = nil
